services:
  frontend:
    image: 654654145459.dkr.ecr.us-east-1.amazonaws.com/ttc-frontend:v5
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          memory: 256M

  backend:
    image: 654654145459.dkr.ecr.us-east-1.amazonaws.com/ttc-backend:v2
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 256M
